The dataSplit.py will split a file in the format

X_start Y_start X_end Y_end  (4 columns, n rows)

x1_s    y1_s    x1_e  y1_e

.
.
.
xn_s    yn_s    xn_e  yn_e


into two files containing the shares of each value

For instance, first file will be as follows:

Share_X_start Share_Y_start  Share_X_end Share_Y_end  (4 columns, n rows)

sh_x11_s        sh_y11_s             sh_x11_e  sh_y11_e
.
.
.
.
sh_xn1_s      sh_yn1_s          sh_xn1_e     sh_yn1_e


Then, since apparently in C++ it is easier to work with .CSV files, the script  xlrs_to_csv.py will convert them to csv

(explain how to run this script)
